const initialData = {
  proposals: {
    'proposal-1': {
      id: 'proposal-1',
      projectType: 'new',
      numPanel: '12',
      brandPanel: 'LG',
      numMicro: '12',
      brandInverter: 'Enphase',
      proposalUrl: 'https://website.io/proposal?id=someuid',
      customerName: 'Peter Parker',
      crewDate: 'March 14th 2022',
      crewName: 'Mike Tyson',
      projectAddress: '123 Andrew Lane, City, State',
      customerConfirmed: true,
      crewConfirmed: true,
    },
    'proposal-2': {
      id: 'proposal-2',
      projectType: 'new',
      numPanel: '12',
      brandPanel: 'LG',
      numMicro: '12',
      brandInverter: 'Enphase',
      proposalUrl: 'https://website.io/proposal?id=someuid',
      customerName: 'Peter Parker',
      crewDate: 'March 14th 2022',
      crewName: 'Mike Tyson',
      projectAddress: '123 Andrew Lane, City, State',
      customerConfirmed: true,
      crewConfirmed: true,
    },
    'proposal-3': {
      id: 'proposal-3',
      projectType: 'new',
      numPanel: '12',
      brandPanel: 'LG',
      numMicro: '12',
      brandInverter: 'Enphase',
      proposalUrl: 'https://website.io/proposal?id=someuid',
      customerName: 'Peter Parker',
      crewDate: 'March 14th 2022',
      crewName: 'Mike Tyson',
      projectAddress: '123 Andrew Lane, City, State',
      customerConfirmed: true,
      crewConfirmed: true,
    },
    'proposal-4': {
      id: 'proposal-4',
      projectType: 'new',
      numPanel: '12',
      brandPanel: 'LG',
      numMicro: '12',
      brandInverter: 'Enphase',
      proposalUrl: 'https://website.io/proposal?id=someuid',
      customerName: 'Peter Parker',
      crewDate: 'March 14th 2022',
      crewName: 'Mike Tyson',
      projectAddress: '123 Andrew Lane, City, State',
      customerConfirmed: true,
      crewConfirmed: true,
    },
    'proposal-5': {
      id: 'proposal-5',
      projectType: 'new',
      numPanel: '12',
      brandPanel: 'LG',
      numMicro: '12',
      brandInverter: 'Enphase',
      proposalUrl: 'https://website.io/proposal?id=someuid',
      customerName: 'Peter Parker',
      crewDate: 'March 14th 2022',
      crewName: 'Mike Tyson',
      projectAddress: '123 Andrew Lane, City, State',
      customerConfirmed: true,
      crewConfirmed: true,
    },
    'proposal-6': {
      id: 'proposal-6',
      projectType: 'new',
      numPanel: '12',
      brandPanel: 'LG',
      numMicro: '12',
      brandInverter: 'Enphase',
      proposalUrl: 'https://website.io/proposal?id=someuid',
      customerName: 'Peter Parker',
      crewDate: 'March 14th 2022',
      crewName: 'Mike Tyson',
      projectAddress: '123 Andrew Lane, City, State',
      customerConfirmed: true,
      crewConfirmed: true,
    },
    'proposal-7': {
      id: 'proposal-7',
      projectType: 'new',
      numPanel: '12',
      brandPanel: 'LG',
      numMicro: '12',
      brandInverter: 'Enphase',
      proposalUrl: 'https://website.io/proposal?id=someuid',
      customerName: 'Peter Parker',
      crewDate: 'March 14th 2022',
      crewName: 'Mike Tyson',
      projectAddress: '123 Andrew Lane, City, State',
      customerConfirmed: true,
      crewConfirmed: true,
    },
    'proposal-8': {
      id: 'proposal-8',
      projectType: 'new',
      numPanel: '12',
      brandPanel: 'LG',
      numMicro: '12',
      brandInverter: 'Enphase',
      proposalUrl: 'https://website.io/proposal?id=someuid',
      customerName: 'Peter Parker',
      crewDate: 'March 14th 2022',
      crewName: 'Mike Tyson',
      projectAddress: '123 Andrew Lane, City, State',
      customerConfirmed: true,
      crewConfirmed: true,
    },
    'proposal-9': {
      id: 'proposal-9',
      projectType: 'new',
      numPanel: '12',
      brandPanel: 'LG',
      numMicro: '12',
      brandInverter: 'Enphase',
      proposalUrl: 'https://website.io/proposal?id=someuid',
      customerName: 'Peter Parker',
      crewDate: 'March 14th 2022',
      crewName: 'Mike Tyson',
      projectAddress: '123 Andrew Lane, City, State',
      customerConfirmed: true,
      crewConfirmed: true,
    },
    'proposal-10': {
      id: 'proposal-10',
      projectType: 'new',
      numPanel: '12',
      brandPanel: 'LG',
      numMicro: '12',
      brandInverter: 'Enphase',
      proposalUrl: 'https://website.io/proposal?id=someuid',
      customerName: 'Peter Parker',
      crewDate: 'March 14th 2022',
      crewName: 'Mike Tyson',
      projectAddress: '123 Andrew Lane, City, State',
      customerConfirmed: true,
      crewConfirmed: true,
    },
    'proposal-11': {
      id: 'proposal-11',
      projectType: 'new',
      numPanel: '12',
      brandPanel: 'LG',
      numMicro: '12',
      brandInverter: 'Enphase',
      proposalUrl: 'https://website.io/proposal?id=someuid',
      customerName: 'Peter Parker',
      crewDate: 'March 14th 2022',
      crewName: 'Mike Tyson',
      projectAddress: '123 Andrew Lane, City, State',
      customerConfirmed: true,
      crewConfirmed: true,
    },
    'proposal-12': {
      id: 'proposal-12',
      projectType: 'new',
      numPanel: '12',
      brandPanel: 'LG',
      numMicro: '12',
      brandInverter: 'Enphase',
      proposalUrl: 'https://website.io/proposal?id=someuid',
      customerName: 'Peter Parker',
      crewDate: 'March 14th 2022',
      crewName: 'Mike Tyson',
      projectAddress: '123 Andrew Lane, City, State',
      customerConfirmed: true,
      crewConfirmed: true,
    },
    'proposal-13': {
      id: 'proposal-13',
      projectType: 'new',
      numPanel: '12',
      brandPanel: 'LG',
      numMicro: '12',
      brandInverter: 'Enphase',
      proposalUrl: 'https://website.io/proposal?id=someuid',
      customerName: 'Peter Parker',
      crewDate: 'March 14th 2022',
      crewName: 'Mike Tyson',
      projectAddress: '123 Andrew Lane, City, State',
      customerConfirmed: true,
      crewConfirmed: true,
    },
    'proposal-14': {
      id: 'proposal-14',
      projectType: 'new',
      numPanel: '12',
      brandPanel: 'LG',
      numMicro: '12',
      brandInverter: 'Enphase',
      proposalUrl: 'https://website.io/proposal?id=someuid',
      customerName: 'Peter Parker',
      crewDate: 'March 14th 2022',
      crewName: 'Mike Tyson',
      projectAddress: '123 Andrew Lane, City, State',
      customerConfirmed: true,
      crewConfirmed: true,
    },
    'proposal-15': {
      id: 'proposal-15',
      projectType: 'new',
      numPanel: '12',
      brandPanel: 'LG',
      numMicro: '12',
      brandInverter: 'Enphase',
      proposalUrl: 'https://website.io/proposal?id=someuid',
      customerName: 'Peter Parker',
      crewDate: 'March 14th 2022',
      crewName: 'Mike Tyson',
      projectAddress: '123 Andrew Lane, City, State',
      customerConfirmed: true,
      crewConfirmed: true,
    },
    'proposal-16': {
      id: 'proposal-16',
      projectType: 'new',
      numPanel: '12',
      brandPanel: 'LG',
      numMicro: '12',
      brandInverter: 'Enphase',
      proposalUrl: 'https://website.io/proposal?id=someuid',
      customerName: 'Peter Parker',
      crewDate: 'March 14th 2022',
      crewName: 'Mike Tyson',
      projectAddress: '123 Andrew Lane, City, State',
      customerConfirmed: true,
      crewConfirmed: true,
    },
    'proposal-17': {
      id: 'proposal-17',
      projectType: 'new',
      numPanel: '12',
      brandPanel: 'LG',
      numMicro: '12',
      brandInverter: 'Enphase',
      proposalUrl: 'https://website.io/proposal?id=someuid',
      customerName: 'Peter Parker',
      crewDate: 'March 14th 2022',
      crewName: 'Mike Tyson',
      projectAddress: '123 Andrew Lane, City, State',
      customerConfirmed: true,
      crewConfirmed: true,
    },
    'proposal-18': {
      id: 'proposal-18',
      projectType: 'new',
      numPanel: '12',
      brandPanel: 'LG',
      numMicro: '12',
      brandInverter: 'Enphase',
      proposalUrl: 'https://website.io/proposal?id=someuid',
      customerName: 'Peter Parker',
      crewDate: 'March 14th 2022',
      crewName: 'Mike Tyson',
      projectAddress: '123 Andrew Lane, City, State',
      customerConfirmed: true,
      crewConfirmed: true,
    },
    'proposal-19': {
      id: 'proposal-19',
      projectType: 'new',
      numPanel: '12',
      brandPanel: 'LG',
      numMicro: '12',
      brandInverter: 'Enphase',
      proposalUrl: 'https://website.io/proposal?id=someuid',
      customerName: 'Peter Parker',
      crewDate: 'March 14th 2022',
      crewName: 'Mike Tyson',
      projectAddress: '123 Andrew Lane, City, State',
      customerConfirmed: true,
      crewConfirmed: true,
    },
    'proposal-20': {
      id: 'proposal-20',
      projectType: 'new ',
      numPanel: '12 x ',
      brandPanel: 'LG ',
      numMicro: '12 x ',
      brandInverter: 'Enphase ',
      proposalUrl: 'https://website.io/proposal?id=someuid',
      customerName: 'Peter Parker',
      crewDate: 'March 14th 2022',
      crewName: 'Mike Tyson',
      projectAddress: '123 Andrew Lane, City, State',
      customerConfirmed: true,
      crewConfirmed: true,
    },
    'proposal-21': {
      id: 'proposal-21',
      projectType: 'new',
      numPanel: '12',
      brandPanel: 'LG',
      numMicro: '12',
      brandInverter: 'Enphase',
      proposalUrl: 'https://website.io/proposal?id=someuid',
      customerName: 'Peter Parker',
      crewDate: 'March 14th 2022',
      crewName: 'Mike Tyson',
      projectAddress: '123 Andrew Lane, City, State',
      customerConfirmed: true,
      crewConfirmed: true,
    },
    'proposal-22': {
      id: 'proposal-22',
      projectType: 'new',
      numPanel: '12',
      brandPanel: 'LG',
      numMicro: '12',
      brandInverter: 'Enphase',
      proposalUrl: 'https://website.io/proposal?id=someuid',
      customerName: 'Peter Parker',
      crewDate: 'March 14th 2022',
      crewName: 'Mike Tyson',
      projectAddress: '123 Andrew Lane, City, State',
      customerConfirmed: true,
      crewConfirmed: true,
    },
    'proposal-23': {
      id: 'proposal-23',
      projectType: 'new',
      numPanel: '12',
      brandPanel: 'LG',
      numMicro: '12',
      brandInverter: 'Enphase',
      proposalUrl: 'https://website.io/proposal?id=someuid',
      customerName: 'Peter Parker',
      crewDate: 'March 14th 2022',
      crewName: 'Mike Tyson',
      projectAddress: '123 Andrew Lane, City, State',
      customerConfirmed: true,
      crewConfirmed: true,
    },
    'proposal-24': {
      id: 'proposal-24',
      projectType: 'new',
      numPanel: '12',
      brandPanel: 'LG',
      numMicro: '12',
      brandInverter: 'Enphase',
      proposalUrl: 'https://website.io/proposal?id=someuid',
      customerName: 'Peter Parker',
      crewDate: 'March 14th 2022',
      crewName: 'Mike Tyson',
      projectAddress: '123 Andrew Lane, City, State',
      customerConfirmed: true,
      crewConfirmed: true,
    },
    'proposal-25': {
      id: 'proposal-25',
      projectType: 'new',
      numPanel: '12',
      brandPanel: 'LG',
      numMicro: '12',
      brandInverter: 'Enphase',
      proposalUrl: 'https://website.io/proposal?id=someuid',
      customerName: 'Peter Parker',
      crewDate: 'March 14th 2022',
      crewName: 'Mike Tyson',
      projectAddress: '123 Andrew Lane, City, State',
      customerConfirmed: true,
      crewConfirmed: true,
    },
  },
  columns: {
    'column-1': {
      id: 'column-1',
      title: 'Monday February 14th',
      proposalIds: ['proposal-1', 'proposal-2', 'proposal-3', 'proposal-4', 'proposal-5'],
    },
    'column-2': {
      id: 'column-2',
      title: 'Tuesday February 15th',
      proposalId: ['proposal-6', 'proposal-7', 'proposal-8', 'proposal-9', 'proposal-10'],
    },
    'column-3': {
      id: 'column-3',
      title: 'Wednesday February 16th',
      proposalId: ['proposal-11', 'proposal-12', 'proposal-13', 'proposal-14', 'proposal-15'],
    },
    'column-4': {
      id: 'column-4',
      title: 'Thursday February 17th',
      proposalId: ['proposal-16', 'proposal-17', 'proposal-18', 'proposal-19', 'proposal-20'],
    },
    'column-5': {
      id: 'column-5',
      title: 'Friday February 18th',
      proposalId: ['proposal-21', 'proposal-22', 'proposal-23', 'proposal-24', 'proposal-25'],
    },
  },
  // Manage reordering of columns
  columnOrder: ['column-1'],
}

export default initialData
